import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { CalendarDays, CheckCircle2, ExternalLink, Link2, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";

export default function Calendar() {
  const { user, loading, isAuthenticated } = useAuth();
  const status = trpc.calendar.status.useQuery(undefined, { enabled: isAuthenticated });
  const connect = trpc.calendar.connect.useQuery(undefined, { enabled: isAuthenticated });

  if (loading) return <main className="grid min-h-screen place-items-center bg-[#f7f8f4] text-sm text-[#718073]">Loading workspace…</main>;
  if (!isAuthenticated) return <main className="grid min-h-screen place-items-center bg-[#f7f8f4] px-5"><div className="max-w-sm rounded-3xl border border-[#dfe8d6] bg-white p-8 text-center shadow-sm"><Sparkles className="mx-auto h-8 w-8 text-[#789c52]" /><h1 className="mt-4 text-2xl font-semibold text-[#173b2d]">Connect your calendar</h1><p className="mt-3 text-sm leading-relaxed text-[#718073]">Sign in as the CoachFlow operator to connect Google Calendar and manage availability.</p><Button className="mt-6 w-full bg-[#173b2d] text-[#eff7de]" onClick={() => startLogin()}>Sign in to continue</Button></div></main>;

  return <main className="min-h-screen bg-[#f7f8f4] px-5 py-8 text-[#172018] sm:py-12"><div className="mx-auto max-w-3xl"><header className="flex items-center justify-between"><Link href="/" className="flex items-center gap-2 text-sm font-semibold text-[#173b2d]"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#173b2d] text-[#d8f27f]"><Sparkles className="h-4 w-4" /></span> CoachFlow</Link><Link href="/" className="text-xs font-semibold text-[#6a8a50]">Back to dashboard</Link></header><section className="mt-12 rounded-[2rem] border border-[#dfe8d6] bg-white p-7 shadow-[0_16px_50px_rgba(45,65,42,0.07)] sm:p-10"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#e8f3d8] text-[#628e45]"><CalendarDays className="h-6 w-6" /></div><p className="mt-7 text-xs font-semibold uppercase tracking-[0.18em] text-[#7a9468]">Booking infrastructure</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.05em] text-[#173b2d]">Connect Google Calendar.</h1><p className="mt-4 max-w-xl text-base leading-relaxed text-[#718073]">CoachFlow will check your availability before offering slots, create a Google Calendar event, invite the prospect, and keep the lead pipeline updated.</p><div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-[#f7f8f4] p-4"><Link2 className="h-5 w-5 text-[#83ad4e]" /><p className="mt-3 text-sm font-semibold">One-time connection</p><p className="mt-1 text-xs leading-relaxed text-[#849085]">OAuth keeps your calendar access private and revocable.</p></div><div className="rounded-2xl bg-[#f7f8f4] p-4"><CalendarDays className="h-5 w-5 text-[#83ad4e]" /><p className="mt-3 text-sm font-semibold">Live availability</p><p className="mt-1 text-xs leading-relaxed text-[#849085]">Only open weekday slots are shown to prospects.</p></div><div className="rounded-2xl bg-[#f7f8f4] p-4"><ShieldCheck className="h-5 w-5 text-[#83ad4e]" /><p className="mt-3 text-sm font-semibold">Secure storage</p><p className="mt-1 text-xs leading-relaxed text-[#849085]">Refresh tokens are encrypted server-side.</p></div></div><div className="mt-8 flex flex-wrap items-center gap-4">{status.data?.connected ? <div className="flex items-center gap-2 rounded-xl bg-[#eff7de] px-4 py-3 text-sm font-semibold text-[#416d3b]"><CheckCircle2 className="h-4 w-4" /> Google Calendar connected</div> : <Button disabled={!connect.data?.url} className="bg-[#173b2d] text-[#eff7de]" onClick={() => { if (connect.data?.url) window.location.href = connect.data.url; }}>Connect Google Calendar <ExternalLink className="ml-2 h-4 w-4" /></Button>}<p className="text-xs text-[#8b968c]">Signed in as {user?.email || user?.name || "CoachFlow operator"}</p></div></section></div></main>;
}
